server:
    port: 8006

spring:
    application:
        name: cloud-provider-consul-payment
    cloud:
#        consul注册中心地址
      consul:
          host: hadoop000
          port: 8500
          discovery:
              #hostname: 127.0.0.1
              service-name: ${spring.application.name}
