server:
    port: 8001

spring:
    application:
        name: cloud-payment-service
    datasource:
        url: jdbc:mysql://localhost:3306/springcloud2024?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
#      &allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
#    redis:
#        host: hadoop000
#        port: 6379
#        database: 0
#        password: Lfy123456

#mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.sun.springcloud.entity
#    configuration:
#        map-underscore-to-camel-case: true

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.sun.springcloud.entity
#    configuration:
#        map-underscore-to-camel-case: true

#eureka:
#  client:
#      register-with-eureka: true  # 默认true
#      fetch-registry: true  # 默认true
#      service-url:
#          defaultZone: http://localhost:7011/eureka/
