server:
    port: 8004

#服务别名，表示注册服务到zookeeper注册中心的名称
spring:
    application:
        name: cloud-provider-zkpayment
#    datasource:
#        url: jdbc:mysql://localhost:3306/springcloud2024?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 123456
#        type: com.alibaba.druid.pool.DruidDataSource
    cloud:
      zookeeper:
          connect-string: hadoop000:2181

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.sun.springcloud.entity
